version: '3.8'

networks:
  community_network:
    driver: bridge

services:
  db:
    image: postgres:latest
    container_name: community_bot_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: community_bot
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - community_network

  community-bot:
    image: community-bot
    depends_on:
      - db
    env_file:
      - config.env
    networks:
      - community_network
    ports:
      - "9091:9091"


volumes:
  db_data: