globalAdministratorIds: ${GLOBAL_ADMINS}
botConfig:
  token: ${BOT_TOKEN}
  path: /community-bot
  username: ${BOT_USERNAME}
  allowedUpdates:
    - update_id
    - message
    - edited_message
    - channel_post
    - edited_channel_post
    - business_connection
    - business_message
    - edited_business_message
    - deleted_business_messages
    - message_reaction
    - message_reaction_count
    - inline_query
    - chosen_inline_result
    - callback_query
    - shipping_query
    - pre_checkout_query
    - purchased_paid_media
    - poll
    - poll_answer
    - my_chat_member
    - chat_member
    - chat_join_request
    - chat_boost
    - removed_chat_boost
appBaseUrl: ${APP_URL}
db:
  jdbcUrl: ${DB_URL:"jdbc:postgresql://localhost:5432/community_bot"}
  username: ${DB_USERNAME:admin}
  password: ${DB_PASSWORD:admin}
  driverClassName: org.postgresql.Driver
  schema: ${DB_SCHEMA:public}
