name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to GitHub Container Registry with PAT
      run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
   
    - name: Build the Docker image
      run: |
        IMAGE_NAME="ghcr.io/$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')/telegram_community_bot"
        TIMESTAMP=$(date +%s)
        docker build . --file Dockerfile --tag $IMAGE_NAME:$TIMESTAMP
        docker push $IMAGE_NAME:$TIMESTAMP
