name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

    - name: Build and Push Docker Image
      run: |
        ORG_NAME="your-org-name"  # Replace with your organization name
        IMAGE_NAME="ghcr.io/$ORG_NAME/telegram_community_bot"
        TIMESTAMP=$(date +%s)
        
        docker build . --file Dockerfile --tag $IMAGE_NAME:$TIMESTAMP
        docker push $IMAGE_NAME:$TIMESTAMP
